name: ESLint & Build Test

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Install dependencies
        run: pnpm install --strict-peer-dependencies=false --no-frozen-lockfile

      - name: Install Turbo
        run: pnpm add turbo --save-dev -w

      - name: Lint Code
        run: turbo lint

      - name: Build Test
        run: turbo run build
