name: ESLint & Build Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
      - feat#*
    paths:
      - 'apps/web/**'
      - '!packages/ui/**'
      - '.github/workflows/ci-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
            apps/web/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Install dependencies
        run: |
          pnpm install --strict-peer-dependencies=false --no-frozen-lockfile
          pnpm add turbo --save-dev -w

      - name: Lint & Build
        run: pnpm turbo typescript lint format build --parallel